### Year 1 Topology 1 Contingency Analysis Reporting - Overloading

In [ ]:
import pandas as pd
import numpy as np

#### Overload Data

In [ ]:
list_flow = []
list_gens = [0, 50, 100]
list_lsc = ['lls', 'rls','hls']
for gen in list_gens:
    for lsc in list_lsc:
        file_out = 'savnw_sol_' + str(gen) +'_'+ lsc + '.xlsx'
        data_flow = pd.read_excel(file_out, sheet_name='Branch Flow')
        data_f_nonan = data_flow.dropna(how='all').reset_index(drop=True)
        data_f_nonan['Scenario']= 'Solar = ' + str(gen) + ' MW, ' + lsc.upper()
        list_flow.append(data_f_nonan)
data_f = pd.concat(list_flow).reset_index(drop=True)
# branches loaded greater than 100% of their rating
bran_flow_load = data_f[data_f['% FLOW']>100].reset_index(drop=True)
print(len(bran_flow_load))
display(bran_flow_load.head())

102

,BRANCH,CONTINGENCY,MVAFLOW,AMPFLOW,RATE RATE1/RATE2,% FLOW,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Scenario
0,3001 MINE 230.00 3003 S. MI...,SING OPN LIN 1 101-151(1),513.168518,496.151459,300.0,165.383820,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"
1,153 MID230 230.00 154 DOWNT...,SING OPN LIN 12 202-203(1),-346.578369,355.408234,350.0,101.545210,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"
2,3001 MINE 230.00 3003 S. MI...,BUS 151,1026.465210,1030.165405,300.0,343.388468,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"
3,3001 MINE 230.00 3011 MINE_...,BUS 151,-1606.048950,1606.048950,1560.0,102.951856,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"
4,3003 S. MINE 230.00 3005 WEST ...,BUS 151,505.931305,515.078247,350.0,147.165213,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"

#### Getting the nonconverged contingencies for each scenario

In [ ]:
list_sum = []
list_gens = [0, 50, 100]
list_lsc = ['lls','rls','hls']
for gen in list_gens:
    for lsc in list_lsc:
        file_out = 'savnw_sol_' + str(gen) +'_'+ lsc + '.xlsx'
        data_flow = pd.read_excel(file_out, sheet_name='Branch Flow')
        data_f_nonan = data_flow.dropna(how='all').reset_index(drop=True)
        data_f_nonan['Scenario']= 'Solar = ' + str(gen) + ' MW, ' + lsc.upper()
        data_summary = pd.read_excel(file_out, sheet_name='Summary')
        data_summary_nonan = data_summary.dropna(how='all').reset_index(drop=True)
        data_cont = data_summary_nonan.loc[135:141].reset_index(drop=True)
        # extracting all the tested contingencies 
        tested_conts = list(data_cont['ACCC SOLUTION SUMMARY'])
        ans_list = "".join(tested_conts)
        cont_tested = ans_list.split(',')
        cont_test = [s.strip() for s in cont_tested]
        # extracting contingencies for the studied scenario
        scen_cont = data_f_nonan['CONTINGENCY'].unique()
        # blown up scenarios 
        scenario = 'Solar = ' + str(gen) + ' MW, ' + lsc.upper()
        list_blown = ', '.join(list(set(cont_test)-set(scen_cont)))
        print(f'For the studied scenario, {scenario}, the tested contingencies {list_blown} did not converge')

For the studied scenario, Solar = 0 MW, LLS, the tested contingencies BUS 154, UNIT 206(1), BUS 201, SING OPN LIN   15 205-206(1), BUS 152 did not converge
For the studied scenario, Solar = 0 MW, RLS, the tested contingencies BUS 154, UNIT 206(1), BUS 201, BUS 151, SING OPN LIN   15 205-206(1), BUS 152 did not converge
For the studied scenario, Solar = 0 MW, HLS, the tested contingencies BUS 154, UNIT 206(1), BUS 201, BUS 151, SING OPN LIN   15 205-206(1), BUS 152, BUS 202 did not converge
For the studied scenario, Solar = 50 MW, LLS, the tested contingencies BUS 152, BUS 154, BUS 201 did not converge
For the studied scenario, Solar = 50 MW, RLS, the tested contingencies BUS 154, UNIT 206(1), BUS 201, SING OPN LIN   15 205-206(1), BUS 152 did not converge
For the studied scenario, Solar = 50 MW, HLS, the tested contingencies BUS 154, UNIT 206(1), BUS 201, BUS 151, SING OPN LIN   15 205-206(1), BUS 152 did not converge
For the studied scenario, Solar = 100 MW, LLS, the tested contingencies BUS 152, BUS 154, BUS 201 did not converge
For the studied scenario, Solar = 100 MW, RLS, the tested contingencies BUS 154, UNIT 206(1), BUS 201, SING OPN LIN   15 205-206(1), BUS 152 did not converge
For the studied scenario, Solar = 100 MW, HLS, the tested contingencies BUS 154, UNIT 206(1), BUS 201, BUS 151, SING OPN LIN   15 205-206(1), BUS 152 did not converge

Getting blown up count per scenario

In [ ]:
list_sum = []
list_gens = [0, 50, 100]
list_lsc = ['lls','rls','hls']
list_blown = []
for gen in list_gens:
    for lsc in list_lsc:
        file_out = 'savnw_sol_' + str(gen) +'_'+ lsc + '.xlsx'
        data_flow = pd.read_excel(file_out, sheet_name='Branch Flow')
        data_f_nonan = data_flow.dropna(how='all').reset_index(drop=True)
        data_f_nonan['Scenario']= 'Solar = ' + str(gen) + ' MW, ' + lsc.upper()
        data_summary = pd.read_excel(file_out, sheet_name='Summary')
        data_summary_nonan = data_summary.dropna(how='all').reset_index(drop=True)
        data_cont = data_summary_nonan.loc[135:141].reset_index(drop=True)
        # extracting all the tested contingencies 
        tested_conts = list(data_cont['ACCC SOLUTION SUMMARY'])
        ans_list = "".join(tested_conts)
        cont_tested = ans_list.split(',')
        cont_test = [s.strip() for s in cont_tested]
        # extracting contingencies for the studied scenario
        scen_cont = data_f_nonan['CONTINGENCY'].unique()
        # blown up scenarios 
        
        scenario = 'Solar = ' + str(gen) + ' MW, ' + lsc.upper()
        
        blown_cont = list(set(cont_test)-set(scen_cont))
        list_blown.extend(blown_cont)

##### Count of scenarios for which tested contingency failed to converge

In [ ]:
from collections import Counter
data = list_blown
counts = Counter(data)
df = pd.DataFrame(list(counts.items()),columns = ['Contingency','Count of Scenarios']).sort_values(by='Count of Scenarios', ascending=False)
display(df)

                    Contingency  Count of Scenarios
0                       BUS 154                   9
2                       BUS 201                   9
4                       BUS 152                   9
1                   UNIT 206(1)                   7
3  SING OPN LIN   15 205-206(1)                   7
5                       BUS 151                   4
6                       BUS 202                   1

#### Branch loading data wrangling

In [ ]:
bran_overload = bran_flow_load.rename(columns={'BRANCH':'Branch',
                                        'CONTINGENCY':'Contingency',
                                        'MVAFLOW': 'MVA Flow',
                                        'AMPFLOW':'AMP Flow',
                                        'RATE RATE1/RATE2':'Rate', 
                                        '% FLOW':'Loading'})
bran_overload['Contingency'] = bran_overload['Contingency'].str.replace('&','\&')
bran_overload['Branch'] = bran_overload['Branch'].str.replace('_','\_')

In [ ]:
print(len(bran_overload))
display(bran_overload.head())

102

,Branch,Contingency,MVA Flow,AMP Flow,Rate,Loading,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Scenario
0,3001 MINE 230.00 3003 S. MI...,SING OPN LIN 1 101-151(1),513.168518,496.151459,300.0,165.383820,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"
1,153 MID230 230.00 154 DOWNT...,SING OPN LIN 12 202-203(1),-346.578369,355.408234,350.0,101.545210,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"
2,3001 MINE 230.00 3003 S. MI...,BUS 151,1026.465210,1030.165405,300.0,343.388468,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"
3,3001 MINE 230.00 3011 MINE\...,BUS 151,-1606.048950,1606.048950,1560.0,102.951856,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"
4,3003 S. MINE 230.00 3005 WEST ...,BUS 151,505.931305,515.078247,350.0,147.165213,NaN,NaN,NaN,NaN,"Solar = 0 MW, LLS"

Overload violations

In [ ]:
list_scen = list(bran_overload['Scenario'].unique())
branch_overload = bran_overload[['Scenario','Branch','Contingency','MVA Flow','AMP Flow','Rate','Loading']]

Unit Fault Contingency loading > 100% and loading > 130%

In [ ]:
print('Unit Fault Contingency loading > 100% and loading > 130%')
print('--------------------------------------------------------------------------------------------------------------------------------')
for scen in list_scen:
    print(scen)
    bran_load_1 = branch_overload[branch_overload['Scenario'] == scen]
    bran_load = bran_load_1[['Branch','Contingency','MVA Flow','AMP Flow','Rate','Loading']]
    unit = bran_load[bran_load['Contingency'].str.contains('UNIT')].reset_index(drop=True)
    if(len(unit) != 0):
        unit_100 = unit[unit['Loading']>100]
        if(len(unit_100) != 0):
            list_ans_single = list([[int(s) for s in m.split() if s.isdigit()] for m in unit_100['Branch'].dropna().unique()])
            ans_single = ', '.join([(str(s[0])+'-'+str(s[1])+'('+ str(s[2])+')') for s in list_ans_single])
            print(f'For the studied scenario {scen}, Loading of > 100% reported for branch(es) {ans_single}')
        unit_130 = unit[unit['Loading']>130]
        if(len(unit_100) != 0):
            list_ans_single = list([[int(s) for s in m.split() if s.isdigit()] for m in unit_130['Branch'].dropna().unique()])
            ans_single = ', '.join([(str(s[0])+'-'+str(s[1])+'('+ str(s[2])+')') for s in list_ans_single])
            print(f'For the studied scenario {scen}, Loading of > 130% reported for branch(es) {ans_single}')
            print('--------------------------------------------------------------------------------------------------------------------------------')

Unit Fault Contingency loading > 100% and loading > 130%
--------------------------------------------------------------------------------------------------------------------------------
Solar = 0 MW, LLS
For the studied scenario Solar = 0 MW, LLS, Loading of > 100% reported for branch(es) 3001-3003(1)
For the studied scenario Solar = 0 MW, LLS, Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 0 MW, RLS
For the studied scenario Solar = 0 MW, RLS, Loading of > 100% reported for branch(es) 3001-3003(1), 205-206(1)
For the studied scenario Solar = 0 MW, RLS, Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 0 MW, HLS
For the studied scenario Solar = 0 MW, HLS, Loading of > 100% reported for branch(es) 3001-3003(1), 101-151(1), 205-206(1)
For the studied scenario Solar = 0 MW, HLS, Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 50 MW, LLS
For the studied scenario Solar = 50 MW, LLS, Loading of > 100% reported for branch(es) 3001-3003(1), 153-154(1), 3005-3007(1)
For the studied scenario Solar = 50 MW, LLS, Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 50 MW, RLS
For the studied scenario Solar = 50 MW, RLS, Loading of > 100% reported for branch(es) 3001-3003(1)
For the studied scenario Solar = 50 MW, RLS, Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 50 MW, HLS
For the studied scenario Solar = 50 MW, HLS, Loading of > 100% reported for branch(es) 3001-3003(1), 205-206(1)
For the studied scenario Solar = 50 MW, HLS, Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 100 MW, LLS
For the studied scenario Solar = 100 MW, LLS, Loading of > 100% reported for branch(es) 3001-3003(1), 153-154(1), 3005-3007(1)
For the studied scenario Solar = 100 MW, LLS, Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 100 MW, RLS
For the studied scenario Solar = 100 MW, RLS, Loading of > 100% reported for branch(es) 3001-3003(1)
For the studied scenario Solar = 100 MW, RLS, Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 100 MW, HLS
For the studied scenario Solar = 100 MW, HLS, Loading of > 100% reported for branch(es) 3001-3003(1), 205-206(1)
For the studied scenario Solar = 100 MW, HLS, Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------

Bus Fault Contingency loading > 100% and loading > 130%

In [ ]:
print('Bus Fault Contingency loading > 100% and loading > 130%')
print('--------------------------------------------------------------------------------------------------------------------------------')
for scen in list_scen:
    print(scen) 
    bran_load_1 = branch_overload[branch_overload['Scenario'] == scen]
    bran_load = bran_load_1[['Branch','Contingency','MVA Flow','AMP Flow','Rate','Loading']]
    bus = bran_load[bran_load['Contingency'].str.contains('BUS')].reset_index(drop=True)
    if len(bus) != 0:
        bus_100 = bus[bus['Loading']>100]
        if(len(bus_100) != 0):
            list_ans_single = list([[int(s) for s in m.split() if s.isdigit()] for m in bus_100['Branch'].dropna().unique()])
            ans_single = ', '.join([(str(s[0])+'-'+str(s[1])+'('+ str(s[2])+')') for s in list_ans_single])
            print(f'Loading of > 100% reported for branch(es) {ans_single}')
        bus_130 = bus[bus['Loading']>130]
        if(len(bus_130) != 0):
            list_ans_single = list([[int(s) for s in m.split() if s.isdigit()] for m in bus_130['Branch'].dropna().unique()])
            ans_single = ', '.join([(str(s[0])+'-'+str(s[1])+'('+ str(s[2])+')') for s in list_ans_single])
            print(f'Loading of > 100% reported for branch(es) {ans_single}')
    print('--------------------------------------------------------------------------------------------------------------------------------')

Bus Fault Contingency loading > 100% and loading > 130%
--------------------------------------------------------------------------------------------------------------------------------
Solar = 0 MW, LLS
Loading of > 100% reported for branch(es) 3001-3003(1), 3001-3011(1), 3003-3005(1), 3003-3005(2), 3005-3007(1), 153-154(1), 154-203(1)
Loading of > 100% reported for branch(es) 3001-3003(1), 3003-3005(1), 3003-3005(2)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 0 MW, RLS
Loading of > 100% reported for branch(es) 153-154(1), 154-203(1)
Loading of > 100% reported for branch(es) 154-203(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 0 MW, HLS
Loading of > 100% reported for branch(es) 154-205(1), 153-154(1), 154-203(1)
Loading of > 100% reported for branch(es) 154-203(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 50 MW, LLS
Loading of > 100% reported for branch(es) 3001-3003(1), 3003-3005(1), 3003-3005(2), 3005-3007(1), 154-203(1)
Loading of > 100% reported for branch(es) 3001-3003(1), 3003-3005(1), 3003-3005(2)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 50 MW, RLS
Loading of > 100% reported for branch(es) 153-3006(1), 3001-3003(1), 3001-3011(1), 3003-3005(1), 3003-3005(2), 3005-3006(1), 3005-3007(1), 153-154(1), 154-203(1)
Loading of > 100% reported for branch(es) 3001-3003(1), 3003-3005(1), 3003-3005(2), 154-203(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 50 MW, HLS
Loading of > 100% reported for branch(es) 153-154(1), 154-203(1)
Loading of > 100% reported for branch(es) 154-203(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 100 MW, LLS
Loading of > 100% reported for branch(es) 3001-3003(1), 3003-3005(1), 3003-3005(2), 154-203(1)
Loading of > 100% reported for branch(es) 3001-3003(1), 3003-3005(1), 3003-3005(2)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 100 MW, RLS
Loading of > 100% reported for branch(es) 3001-3003(1), 3001-3011(1), 3003-3005(1), 3003-3005(2), 3005-3007(1), 154-203(1)
Loading of > 100% reported for branch(es) 3001-3003(1), 3003-3005(1), 3003-3005(2)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 100 MW, HLS
Loading of > 100% reported for branch(es) 153-154(1), 154-203(1)
Loading of > 100% reported for branch(es) 154-203(1)
--------------------------------------------------------------------------------------------------------------------------------

In [ ]:
print('Single Line Open Contingency loading > 100% and loading > 130%')
print('--------------------------------------------------------------------------------------------------------------------------------')
for scen in list_scen:
    print(scen)
    bran_load_1 = branch_overload[branch_overload['Scenario'] == scen]
    bran_load = bran_load_1[['Branch','Contingency','MVA Flow','AMP Flow','Rate','Loading']]
    single = bran_load[bran_load['Contingency'].str.contains('SING OPN LIN')]
    if len(single) != 0:
        single_100 = single[single['Loading']>100]
        if len(single_100) != 0:
            list_ans_single = list([[int(s) for s in m.split() if s.isdigit()] for m in single_100['Branch'].dropna().unique()])
            ans_single = ', '.join([(str(s[0])+'-'+str(s[1])+'('+ str(s[2])+')') for s in list_ans_single])
            print(f'Loading of > 100% reported for branch(es) {ans_single}')
        single_130 = single[single['Loading']>130]
        if len(single_130) != 0:
            list_ans_single = list([[int(s) for s in m.split() if s.isdigit()] for m in single_130['Branch'].dropna().unique()])
            ans_single = ', '.join([(str(s[0])+'-'+str(s[1])+'('+ str(s[2])+')') for s in list_ans_single])
            print(f'Loading of > 130% reported for branch(es) {ans_single}')
            print('--------------------------------------------------------------------------------------------------------------------------------')

Single Line Open Contingency loading > 100% and loading > 130%
--------------------------------------------------------------------------------------------------------------------------------
Solar = 0 MW, LLS
Loading of > 100% reported for branch(es) 3001-3003(1), 153-154(1)
Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 0 MW, RLS
Loading of > 100% reported for branch(es) 3001-3003(1), 154-205(1), 153-154(1), 205-206(1)
Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 0 MW, HLS
Loading of > 100% reported for branch(es) 3001-3003(1), 101-151(1), 154-205(1), 153-154(1), 205-206(1)
Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 50 MW, LLS
Loading of > 100% reported for branch(es) 3001-3003(1), 153-154(1), 3005-3007(1)
Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 50 MW, RLS
Loading of > 100% reported for branch(es) 3001-3003(1), 154-205(1), 153-154(1)
Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 50 MW, HLS
Loading of > 100% reported for branch(es) 3001-3003(1), 154-205(1), 153-154(1), 205-206(1)
Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 100 MW, LLS
Loading of > 100% reported for branch(es) 3001-3003(1), 153-154(1), 3005-3007(1)
Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 100 MW, RLS
Loading of > 100% reported for branch(es) 3001-3003(1)
Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------
Solar = 100 MW, HLS
Loading of > 100% reported for branch(es) 3001-3003(1), 154-205(1), 153-154(1), 205-206(1)
Loading of > 130% reported for branch(es) 3001-3003(1)
--------------------------------------------------------------------------------------------------------------------------------

Branch Overload Summary - grouped by Scenario and Contingency - Branch Overload Chapter

In [ ]:
data_fil_overload = bran_overload[['Scenario', 'Branch', 'Contingency']].drop_duplicates()
list_ans_bran = list([[int(s) for s in m.split() if s.isdigit()] for m in data_fil_overload['Branch'].dropna().unique()])
bran_new = [(str(s[0])+'-'+str(s[1])+'('+ str(s[2])+')') for s in list_ans_bran]
bran_replace = data_fil_overload['Branch'].unique()
overload_new = data_fil_overload.replace(to_replace=bran_replace, value=bran_new)
# getting the count of overload
pivot_table_overload = pd.DataFrame(pd.pivot_table(data_fil_overload, index= ['Scenario','Contingency'],values = 'Branch', aggfunc='count').to_records())

In [ ]:
# getting the list of branch overload 
pivot_overload = pd.DataFrame(pd.pivot(overload_new, index= ['Scenario','Contingency'], columns = 'Branch',values = 'Branch').to_records())
pivot_overload['Branches'] = pivot_overload['101-151(1)'].astype(str).str.cat(pivot_overload[['153-154(1)', '153-3006(1)','154-203(1)', '154-205(1)', '205-206(1)', '3001-3003(1)',
                            '3001-3011(1)', '3003-3005(1)', '3003-3005(2)', '3005-3006(1)','3005-3007(1)']].astype(str), sep=',')
pivot_overload['Branches'] = pivot_overload['Branches'].str.replace(',nan','').str.replace('nan,','')
pivot_load = pivot_overload.drop(columns = list(overload_new['Branch'].unique()))

In [ ]:
pivot_table_overload = pd.DataFrame(pd.pivot_table(data_fil_overload, index= ['Scenario','Contingency'],values = 'Branch', aggfunc='count').to_records())
pivot_table_load = pivot_table_overload.rename(columns = {'Branch':'Branch Count'})
df_load = pd.merge(pivot_load, pivot_table_load, on=['Scenario','Contingency']).sort_values(by='Branch Count', ascending=False).reset_index(drop=True)
df_load.head(10)

,Scenario,Contingency,Branches,Branch Count
0,"Solar = 50 MW, RLS",BUS 151,"153-3006(1),3001-3003(1),3001-3011(1),3003-300...",7
1,"Solar = 0 MW, LLS",BUS 151,"3001-3003(1),3001-3011(1),3003-3005(1),3003-30...",5
2,"Solar = 100 MW, RLS",BUS 151,"3001-3003(1),3001-3011(1),3003-3005(1),3003-30...",5
3,"Solar = 50 MW, LLS",BUS 151,"3001-3003(1),3003-3005(1),3003-3005(2),3005-30...",4
4,"Solar = 50 MW, LLS",SING OPN LIN 15 205-206(1),"153-154(1),3001-3003(1),3005-3007(1)",3

Overload Count - Scenarios

In [ ]:
overload_index = list(bran_overload['Scenario'].value_counts().index)
overload_counts = list(bran_overload['Scenario'].value_counts())
dict_ol_count = {
    'Scenario':overload_index,
    'Overload Counts':overload_counts
}
overload_conclusion  = pd.DataFrame(dict_ol_count)
overload_conclusion

              Scenario  Overload Counts
0   Solar = 50 MW, RLS               14
1    Solar = 0 MW, HLS               13
2   Solar = 50 MW, LLS               13
3  Solar = 100 MW, LLS               12
4   Solar = 50 MW, HLS               11
5  Solar = 100 MW, HLS               11
6    Solar = 0 MW, LLS               10
7    Solar = 0 MW, RLS               10
8  Solar = 100 MW, RLS                8

Overload Count - Branches

In [ ]:
list_cont_load = list(bran_overload['Branch'].unique())
list_scen_count_cont = []
list_cont = []
list_scen_cont = []
for cont in list_cont_load:
    bran_load_cont = bran_overload[bran_overload['Branch'] == cont]
    
    no_scenload_cont = len(list(bran_load_cont['Scenario']))
    list_scen_count_cont.append(no_scenload_cont)
    list_ans_cont = list(bran_load_cont['Branch'].unique())
    list_ans_bran = list([[int(s) for s in m.split() if s.isdigit()] for m in bran_load_cont['Branch'].dropna().unique()])
    bran_new = [(str(s[0])+'-'+str(s[1])+'('+ str(s[2])+')') for s in list_ans_bran]
    ans_bran = ', '.join(bran_new)
    list_cont.append(ans_bran)
    ans_scen_cont = ', '.join(bran_load_cont['Scenario'].unique())
    list_scen_cont.append(ans_scen_cont)

dict_overload_bran_cont = {
                    'Branch': list_cont,
                    'Overload Count':list_scen_count_cont,
                    'Scenarios': list_scen_cont
                  
                }
summary_count_load_bran_scen= pd.DataFrame(dict_overload_bran_cont, columns=[ 'Branch','Overload Count']).sort_values(by = 'Overload Count', ascending=False).reset_index(drop=True)
summary_count_load_bran_scen

          Branch  Overload Count
0   3001-3003(1)              27
1     153-154(1)              27
2     154-203(1)               9
3   3005-3007(1)               8
4     205-206(1)               8
5     154-205(1)               6
6   3003-3005(1)               5
7   3003-3005(2)               5
8   3001-3011(1)               3
9     101-151(1)               2
10   153-3006(1)               1
11  3005-3006(1)               1

Overload Count - Contingencies

In [ ]:
list_cont_load = list(bran_overload['Contingency'].unique())

list_scen_count_cont = []
list_cont = []
list_scen_cont = []
for cont in list_cont_load:
    bran_load_cont = bran_overload[bran_overload['Contingency'] == cont]
    
    no_scenload_cont = len(list(bran_load_cont['Scenario']))
    list_scen_count_cont.append(no_scenload_cont)
    list_ans_cont = list(bran_load_cont['Contingency'].unique())
    ans_bran = ', '.join(list_ans_cont)
    list_cont.append(ans_bran)
    ans_scen_cont = ', '.join(bran_load_cont['Scenario'].unique())
    list_scen_cont.append(ans_scen_cont)

dict_overload_bran_cont = {
                    'Contingency': list_cont,
                    'Overload Count':list_scen_count_cont,
                    'Scenarios': list_scen_cont
                  
                }
summary_overload_cont= pd.DataFrame(dict_overload_bran_cont, columns=[ 'Contingency','Overload Count']).sort_values(by = 'Overload Count', ascending=False).reset_index(drop= True)
summary_overload_cont

                       Contingency  Overload Count
0                          BUS 151              24
1                          BUS 205              14
2      SING OPN LIN   1 101-151(1)               9
3                      UNIT 101(1)               9
4     SING OPN LIN   12 202-203(1)               6
5                          BUS 203               6
6     SING OPN LIN   15 205-206(1)               6
7                      UNIT 206(1)               6
8      SING OPN LIN   6 152-153(1)               5
9   SING OPN LIN   10 201-205(\&1)               4
10    SING OPN LIN   11 201-211(1)               4
11                     UNIT 211(1)               4
12                         BUS 202               2
13     SING OPN LIN   2 102-151(1)               1
14                         BUS 153               1
15                     UNIT 102(1)               1